/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TagsRouteImport } from "./routes/tags";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as GraphRouteImport } from "./routes/graph";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ChunksIndexRouteImport } from "./routes/chunks.index";
import { Route as ChunksNewRouteImport } from "./routes/chunks.new";
import { Route as ChunksChunkIdRouteImport } from "./routes/chunks.$chunkId";
import { Route as ChunksChunkIdEditRouteImport } from "./routes/chunks.$chunkId.edit";

const TagsRoute = TagsRouteImport.update({
  id: "/tags",
  path: "/tags",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const GraphRoute = GraphRouteImport.update({
  id: "/graph",
  path: "/graph",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ChunksIndexRoute = ChunksIndexRouteImport.update({
  id: "/chunks/",
  path: "/chunks/",
  getParentRoute: () => rootRouteImport,
} as any);
const ChunksNewRoute = ChunksNewRouteImport.update({
  id: "/chunks/new",
  path: "/chunks/new",
  getParentRoute: () => rootRouteImport,
} as any);
const ChunksChunkIdRoute = ChunksChunkIdRouteImport.update({
  id: "/chunks/$chunkId",
  path: "/chunks/$chunkId",
  getParentRoute: () => rootRouteImport,
} as any);
const ChunksChunkIdEditRoute = ChunksChunkIdEditRouteImport.update({
  id: "/edit",
  path: "/edit",
  getParentRoute: () => ChunksChunkIdRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/graph": typeof GraphRoute;
  "/login": typeof LoginRoute;
  "/tags": typeof TagsRoute;
  "/chunks/$chunkId": typeof ChunksChunkIdRouteWithChildren;
  "/chunks/new": typeof ChunksNewRoute;
  "/chunks/": typeof ChunksIndexRoute;
  "/chunks/$chunkId/edit": typeof ChunksChunkIdEditRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/graph": typeof GraphRoute;
  "/login": typeof LoginRoute;
  "/tags": typeof TagsRoute;
  "/chunks/$chunkId": typeof ChunksChunkIdRouteWithChildren;
  "/chunks/new": typeof ChunksNewRoute;
  "/chunks": typeof ChunksIndexRoute;
  "/chunks/$chunkId/edit": typeof ChunksChunkIdEditRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/graph": typeof GraphRoute;
  "/login": typeof LoginRoute;
  "/tags": typeof TagsRoute;
  "/chunks/$chunkId": typeof ChunksChunkIdRouteWithChildren;
  "/chunks/new": typeof ChunksNewRoute;
  "/chunks/": typeof ChunksIndexRoute;
  "/chunks/$chunkId/edit": typeof ChunksChunkIdEditRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/graph"
    | "/login"
    | "/tags"
    | "/chunks/$chunkId"
    | "/chunks/new"
    | "/chunks/"
    | "/chunks/$chunkId/edit";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/dashboard"
    | "/graph"
    | "/login"
    | "/tags"
    | "/chunks/$chunkId"
    | "/chunks/new"
    | "/chunks"
    | "/chunks/$chunkId/edit";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/graph"
    | "/login"
    | "/tags"
    | "/chunks/$chunkId"
    | "/chunks/new"
    | "/chunks/"
    | "/chunks/$chunkId/edit";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRoute;
  GraphRoute: typeof GraphRoute;
  LoginRoute: typeof LoginRoute;
  TagsRoute: typeof TagsRoute;
  ChunksChunkIdRoute: typeof ChunksChunkIdRouteWithChildren;
  ChunksNewRoute: typeof ChunksNewRoute;
  ChunksIndexRoute: typeof ChunksIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/tags": {
      id: "/tags";
      path: "/tags";
      fullPath: "/tags";
      preLoaderRoute: typeof TagsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/graph": {
      id: "/graph";
      path: "/graph";
      fullPath: "/graph";
      preLoaderRoute: typeof GraphRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/chunks/": {
      id: "/chunks/";
      path: "/chunks";
      fullPath: "/chunks/";
      preLoaderRoute: typeof ChunksIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/chunks/new": {
      id: "/chunks/new";
      path: "/chunks/new";
      fullPath: "/chunks/new";
      preLoaderRoute: typeof ChunksNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/chunks/$chunkId": {
      id: "/chunks/$chunkId";
      path: "/chunks/$chunkId";
      fullPath: "/chunks/$chunkId";
      preLoaderRoute: typeof ChunksChunkIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/chunks/$chunkId/edit": {
      id: "/chunks/$chunkId/edit";
      path: "/edit";
      fullPath: "/chunks/$chunkId/edit";
      preLoaderRoute: typeof ChunksChunkIdEditRouteImport;
      parentRoute: typeof ChunksChunkIdRoute;
    };
  }
}

interface ChunksChunkIdRouteChildren {
  ChunksChunkIdEditRoute: typeof ChunksChunkIdEditRoute;
}

const ChunksChunkIdRouteChildren: ChunksChunkIdRouteChildren = {
  ChunksChunkIdEditRoute: ChunksChunkIdEditRoute,
};

const ChunksChunkIdRouteWithChildren = ChunksChunkIdRoute._addFileChildren(
  ChunksChunkIdRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GraphRoute: GraphRoute,
  LoginRoute: LoginRoute,
  TagsRoute: TagsRoute,
  ChunksChunkIdRoute: ChunksChunkIdRouteWithChildren,
  ChunksNewRoute: ChunksNewRoute,
  ChunksIndexRoute: ChunksIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
