/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as VocabularyRouteImport } from "./routes/vocabulary";
import { Route as TemplatesRouteImport } from "./routes/templates";
import { Route as TagsRouteImport } from "./routes/tags";
import { Route as RequirementsRouteImport } from "./routes/requirements";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as KnowledgeHealthRouteImport } from "./routes/knowledge-health";
import { Route as GraphRouteImport } from "./routes/graph";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as CodebasesRouteImport } from "./routes/codebases";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ChunksIndexRouteImport } from "./routes/chunks.index";
import { Route as RequirementsNewRouteImport } from "./routes/requirements_.new";
import { Route as RequirementsRequirementIdRouteImport } from "./routes/requirements_.$requirementId";
import { Route as ChunksNewRouteImport } from "./routes/chunks.new";
import { Route as ChunksChunkIdRouteImport } from "./routes/chunks.$chunkId";
import { Route as ChunksChunkIdEditRouteImport } from "./routes/chunks.$chunkId_.edit";

const VocabularyRoute = VocabularyRouteImport.update({
  id: "/vocabulary",
  path: "/vocabulary",
  getParentRoute: () => rootRouteImport,
} as any);
const TemplatesRoute = TemplatesRouteImport.update({
  id: "/templates",
  path: "/templates",
  getParentRoute: () => rootRouteImport,
} as any);
const TagsRoute = TagsRouteImport.update({
  id: "/tags",
  path: "/tags",
  getParentRoute: () => rootRouteImport,
} as any);
const RequirementsRoute = RequirementsRouteImport.update({
  id: "/requirements",
  path: "/requirements",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const KnowledgeHealthRoute = KnowledgeHealthRouteImport.update({
  id: "/knowledge-health",
  path: "/knowledge-health",
  getParentRoute: () => rootRouteImport,
} as any);
const GraphRoute = GraphRouteImport.update({
  id: "/graph",
  path: "/graph",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const CodebasesRoute = CodebasesRouteImport.update({
  id: "/codebases",
  path: "/codebases",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ChunksIndexRoute = ChunksIndexRouteImport.update({
  id: "/chunks/",
  path: "/chunks/",
  getParentRoute: () => rootRouteImport,
} as any);
const RequirementsNewRoute = RequirementsNewRouteImport.update({
  id: "/requirements_/new",
  path: "/requirements/new",
  getParentRoute: () => rootRouteImport,
} as any);
const RequirementsRequirementIdRoute =
  RequirementsRequirementIdRouteImport.update({
    id: "/requirements_/$requirementId",
    path: "/requirements/$requirementId",
    getParentRoute: () => rootRouteImport,
  } as any);
const ChunksNewRoute = ChunksNewRouteImport.update({
  id: "/chunks/new",
  path: "/chunks/new",
  getParentRoute: () => rootRouteImport,
} as any);
const ChunksChunkIdRoute = ChunksChunkIdRouteImport.update({
  id: "/chunks/$chunkId",
  path: "/chunks/$chunkId",
  getParentRoute: () => rootRouteImport,
} as any);
const ChunksChunkIdEditRoute = ChunksChunkIdEditRouteImport.update({
  id: "/chunks/$chunkId_/edit",
  path: "/chunks/$chunkId/edit",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/codebases": typeof CodebasesRoute;
  "/dashboard": typeof DashboardRoute;
  "/graph": typeof GraphRoute;
  "/knowledge-health": typeof KnowledgeHealthRoute;
  "/login": typeof LoginRoute;
  "/requirements": typeof RequirementsRoute;
  "/tags": typeof TagsRoute;
  "/templates": typeof TemplatesRoute;
  "/vocabulary": typeof VocabularyRoute;
  "/chunks/$chunkId": typeof ChunksChunkIdRoute;
  "/chunks/new": typeof ChunksNewRoute;
  "/requirements/$requirementId": typeof RequirementsRequirementIdRoute;
  "/requirements/new": typeof RequirementsNewRoute;
  "/chunks/": typeof ChunksIndexRoute;
  "/chunks/$chunkId/edit": typeof ChunksChunkIdEditRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/codebases": typeof CodebasesRoute;
  "/dashboard": typeof DashboardRoute;
  "/graph": typeof GraphRoute;
  "/knowledge-health": typeof KnowledgeHealthRoute;
  "/login": typeof LoginRoute;
  "/requirements": typeof RequirementsRoute;
  "/tags": typeof TagsRoute;
  "/templates": typeof TemplatesRoute;
  "/vocabulary": typeof VocabularyRoute;
  "/chunks/$chunkId": typeof ChunksChunkIdRoute;
  "/chunks/new": typeof ChunksNewRoute;
  "/requirements/$requirementId": typeof RequirementsRequirementIdRoute;
  "/requirements/new": typeof RequirementsNewRoute;
  "/chunks": typeof ChunksIndexRoute;
  "/chunks/$chunkId/edit": typeof ChunksChunkIdEditRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/codebases": typeof CodebasesRoute;
  "/dashboard": typeof DashboardRoute;
  "/graph": typeof GraphRoute;
  "/knowledge-health": typeof KnowledgeHealthRoute;
  "/login": typeof LoginRoute;
  "/requirements": typeof RequirementsRoute;
  "/tags": typeof TagsRoute;
  "/templates": typeof TemplatesRoute;
  "/vocabulary": typeof VocabularyRoute;
  "/chunks/$chunkId": typeof ChunksChunkIdRoute;
  "/chunks/new": typeof ChunksNewRoute;
  "/requirements_/$requirementId": typeof RequirementsRequirementIdRoute;
  "/requirements_/new": typeof RequirementsNewRoute;
  "/chunks/": typeof ChunksIndexRoute;
  "/chunks/$chunkId_/edit": typeof ChunksChunkIdEditRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/codebases"
    | "/dashboard"
    | "/graph"
    | "/knowledge-health"
    | "/login"
    | "/requirements"
    | "/tags"
    | "/templates"
    | "/vocabulary"
    | "/chunks/$chunkId"
    | "/chunks/new"
    | "/requirements/$requirementId"
    | "/requirements/new"
    | "/chunks/"
    | "/chunks/$chunkId/edit";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/codebases"
    | "/dashboard"
    | "/graph"
    | "/knowledge-health"
    | "/login"
    | "/requirements"
    | "/tags"
    | "/templates"
    | "/vocabulary"
    | "/chunks/$chunkId"
    | "/chunks/new"
    | "/requirements/$requirementId"
    | "/requirements/new"
    | "/chunks"
    | "/chunks/$chunkId/edit";
  id:
    | "__root__"
    | "/"
    | "/codebases"
    | "/dashboard"
    | "/graph"
    | "/knowledge-health"
    | "/login"
    | "/requirements"
    | "/tags"
    | "/templates"
    | "/vocabulary"
    | "/chunks/$chunkId"
    | "/chunks/new"
    | "/requirements_/$requirementId"
    | "/requirements_/new"
    | "/chunks/"
    | "/chunks/$chunkId_/edit";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CodebasesRoute: typeof CodebasesRoute;
  DashboardRoute: typeof DashboardRoute;
  GraphRoute: typeof GraphRoute;
  KnowledgeHealthRoute: typeof KnowledgeHealthRoute;
  LoginRoute: typeof LoginRoute;
  RequirementsRoute: typeof RequirementsRoute;
  TagsRoute: typeof TagsRoute;
  TemplatesRoute: typeof TemplatesRoute;
  VocabularyRoute: typeof VocabularyRoute;
  ChunksChunkIdRoute: typeof ChunksChunkIdRoute;
  ChunksNewRoute: typeof ChunksNewRoute;
  RequirementsRequirementIdRoute: typeof RequirementsRequirementIdRoute;
  RequirementsNewRoute: typeof RequirementsNewRoute;
  ChunksIndexRoute: typeof ChunksIndexRoute;
  ChunksChunkIdEditRoute: typeof ChunksChunkIdEditRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/vocabulary": {
      id: "/vocabulary";
      path: "/vocabulary";
      fullPath: "/vocabulary";
      preLoaderRoute: typeof VocabularyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/templates": {
      id: "/templates";
      path: "/templates";
      fullPath: "/templates";
      preLoaderRoute: typeof TemplatesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tags": {
      id: "/tags";
      path: "/tags";
      fullPath: "/tags";
      preLoaderRoute: typeof TagsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/requirements": {
      id: "/requirements";
      path: "/requirements";
      fullPath: "/requirements";
      preLoaderRoute: typeof RequirementsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/knowledge-health": {
      id: "/knowledge-health";
      path: "/knowledge-health";
      fullPath: "/knowledge-health";
      preLoaderRoute: typeof KnowledgeHealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/graph": {
      id: "/graph";
      path: "/graph";
      fullPath: "/graph";
      preLoaderRoute: typeof GraphRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/codebases": {
      id: "/codebases";
      path: "/codebases";
      fullPath: "/codebases";
      preLoaderRoute: typeof CodebasesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/chunks/": {
      id: "/chunks/";
      path: "/chunks";
      fullPath: "/chunks/";
      preLoaderRoute: typeof ChunksIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/requirements_/new": {
      id: "/requirements_/new";
      path: "/requirements/new";
      fullPath: "/requirements/new";
      preLoaderRoute: typeof RequirementsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/requirements_/$requirementId": {
      id: "/requirements_/$requirementId";
      path: "/requirements/$requirementId";
      fullPath: "/requirements/$requirementId";
      preLoaderRoute: typeof RequirementsRequirementIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/chunks/new": {
      id: "/chunks/new";
      path: "/chunks/new";
      fullPath: "/chunks/new";
      preLoaderRoute: typeof ChunksNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/chunks/$chunkId": {
      id: "/chunks/$chunkId";
      path: "/chunks/$chunkId";
      fullPath: "/chunks/$chunkId";
      preLoaderRoute: typeof ChunksChunkIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/chunks/$chunkId_/edit": {
      id: "/chunks/$chunkId_/edit";
      path: "/chunks/$chunkId/edit";
      fullPath: "/chunks/$chunkId/edit";
      preLoaderRoute: typeof ChunksChunkIdEditRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodebasesRoute: CodebasesRoute,
  DashboardRoute: DashboardRoute,
  GraphRoute: GraphRoute,
  KnowledgeHealthRoute: KnowledgeHealthRoute,
  LoginRoute: LoginRoute,
  RequirementsRoute: RequirementsRoute,
  TagsRoute: TagsRoute,
  TemplatesRoute: TemplatesRoute,
  VocabularyRoute: VocabularyRoute,
  ChunksChunkIdRoute: ChunksChunkIdRoute,
  ChunksNewRoute: ChunksNewRoute,
  RequirementsRequirementIdRoute: RequirementsRequirementIdRoute,
  RequirementsNewRoute: RequirementsNewRoute,
  ChunksIndexRoute: ChunksIndexRoute,
  ChunksChunkIdEditRoute: ChunksChunkIdEditRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
