/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_chunks"];
        put?: never;
        post: operations["create_chunk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chunks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_chunk"];
        put?: never;
        post?: never;
        delete: operations["delete_chunk"];
        options?: never;
        head?: never;
        patch: operations["update_chunk"];
        trace?: never;
    };
    "/api/chunks/{id}/applies-to": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_applies_to"];
        put: operations["put_applies_to"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chunks/{id}/file-refs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_file_refs"];
        put: operations["put_file_refs"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chunks/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chunk_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppliesTo: {
            chunkId: string;
            id: string;
            pattern: string;
        };
        /**
         * @description `camelCase` serialisation is mandatory, not cosmetic: the 106 web files
         *     that consume this API were written against Drizzle's camelCase output.
         *     Emitting snake_case would silently break every one of them.
         */
        Chunk: {
            /** Format: date-time */
            archivedAt?: string | null;
            consequences?: string | null;
            content: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            origin: string;
            rationale?: string | null;
            reviewStatus: string;
            summary?: string | null;
            title: string;
            type: string;
            /** Format: date-time */
            updatedAt: string;
            userId: string;
        };
        ChunkVersion: {
            chunkId: string;
            consequences?: string | null;
            content: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            rationale?: string | null;
            title: string;
            type: string;
            /** Format: int32 */
            version: number;
        };
        CreateChunkBody: {
            content?: string;
            rationale?: string | null;
            title: string;
            type?: string | null;
        };
        FileRef: {
            chunkId: string;
            id: string;
            path: string;
        };
        PathsBody: {
            paths: string[];
        };
        PatternsBody: {
            patterns: string[];
        };
        /** @enum {string} */
        Sort: "newest" | "oldest" | "alpha" | "updated";
        UpdateChunkBody: {
            consequences?: string | null;
            content?: string | null;
            rationale?: string | null;
            title?: string | null;
            type?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_chunks: {
        parameters: {
            query?: {
                type?: string | null;
                search?: string | null;
                origin?: string | null;
                reviewStatus?: string | null;
                sort?: null | components["schemas"]["Sort"];
                limit?: string | null;
                offset?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chunk"][];
                };
            };
        };
    };
    create_chunk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChunkBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chunk"];
                };
            };
        };
    };
    get_chunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chunk"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_chunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_chunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChunkBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chunk"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_applies_to: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppliesTo"][];
                };
            };
        };
    };
    put_applies_to: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatternsBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppliesTo"][];
                };
            };
        };
    };
    get_file_refs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileRef"][];
                };
            };
        };
    };
    put_file_refs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathsBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileRef"][];
                };
            };
        };
    };
    chunk_history: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkVersion"][];
                };
            };
        };
    };
}
